plugins {
    id 'java-library'
    id 'maven-publish'
}

project.ext.projectName = "comet-renderer"
version = project.main_version

apply from: file("scripts/opengl.gradle")
apply from: file("scripts/utils.gradle")
apply from: file("scripts/publishing.gradle")

dependencies {
    implementation "com.ferra13671:gl-texture-utils:${gl_texture_utils_version}"
}